variables:
  kubeloginVersion: v0.0.10 # see https://github.com/Azure/kubelogin/releases


  # Container Registry
  acrConnection:    aksarchitect-acr

  # Pipeline conditions
  isMain:           ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  isProduction:     ${{ eq(variables['Build.SourceBranch'], 'refs/heads/production') }}
  isTag:            ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}
  isFork:           ${{ eq(variables['System.PullRequest.IsFork'], 'True') }}
  isPR:             ${{ eq(variables['Build.Reason'], 'PullRequest') }}
  isScheduled:      ${{ eq(variables['Build.Reason'], 'Schedule') }}
  isTrustedCI:      ${{ and( eq(variables.isFork,'False'), eq(variables.isPR,'False'), eq(variables.isScheduled,'False') ) }}
  deployMain:       ${{ and( eq(variables.isMain,'True'), eq(variables.isTrustedCI,'True') ) }}

  # Docker
  dockerRegistry:   aksarchitect.azurecr.io
  imageName:        aks-archtitect
  ${{ if eq(variables.isTag, 'True') }}:
    imageTag:       ${{ replace(variables['Build.SourceBranch'], 'refs/tags/v', '') }}
  dockerImage:      ${{ variables.dockerRegistry }}/${{ variables.imageName }}
