steps:
- task: NodeTool@0
  displayName: Setup Node.js
  inputs:
    versionSpec: '14.x'

- script: |
    npm ci
    npm install chromedriver --chromedriver_version=LATEST
  displayName: npm install

- script: |
    echo "##vso[task.setvariable variable=commitSha]$(git rev-parse --short HEAD)"
  displayName: Get commit sha

# This UI driven test goes to the specified website
# and checks the page title to be "Hello Azureâ€¦"
# For details, see /deployment.test.js
- script: |
    npm run confirm-deployment
  displayName: Open URL in browser to confirm deployment
  env:
    SELENIUM_TARGET_URL: $(deploymentUrl)
    APP_BUILD_SHA: $(commitSha)
